import localFont from "next/font/local";
import "./globals.css";
import { Inter, Raleway } from 'next/font/google'
import AppContext from '@/state/appContext';
 
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-inter",
})

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-raleway",
  weight: ['300', '400', '700', '900']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${inter.variable} antialiased`}
      >
        <AppContext>
        {children}
        </AppContext>
      </body>
    </html>
  );
}
